Fix bug with principal variation memory
If the Genetic_AI
        1. makes a forced move (that is, it only has one choice) and
        2. it has memory of a principal variation and
        3. the next move of that variation is not followed by the other player, then the next move in the
then the next move of the variation may be illegal, leading to an error
when that illegal move is search for first (the std::iter_swap() call in
search_game_tree()).

Given such specific circumstances, this bug rarely manifested, even
after thousands of games. So, this time I'm leaving the debugging code
in place, just in case something even more subtle manifests. Since the
debugging code is inside a block controlled by a simple iterator
comparison, the performance impact should be negligible.

For reference, here's the game that revealed the bug:

Final future board state at time of error:

       +-------+-------+-------+-------+-------+-------+-------+-------+
       |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
     8 |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
       |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |:::::::|       |:::::::|       |:::::::|       |:::::::|       |
     7 |:::::::|       |:::::::|       |:::::::|       |:::::::|       |
       |:::::::|       |:::::::|       |:::::::|       |:::::::|       |
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |       |:  _  :|       |:::::::|       |:::::::|       |: /") :|
     6 |       |: (#) :|       |:::::::|       |:::::::|       |: 7#( :|
       |       |:/###\:|       |:::::::|       |:::::::|       |:/###\:|
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |:::::::|       |:::::::|       |: \+/ :|       |:::::::|   _   |
     5 |:::::::|       |:::::::|       |: |#| :|       |:::::::|  (#)  |
       |:::::::|       |:::::::|       |:/###\:|       |:::::::| /###\ |
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
     4 |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
       |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |:::::::|       |:::::::|       |:::::::|  \+/  |:::::::|       |
     3 |:::::::|       |:::::::|       |:::::::|  | |  |:::::::|       |
       |:::::::|       |:::::::|       |:::::::| /___\ |:::::::|       |
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |       |:::::::|  |U|  |:::::::|       |:::::::|       |:::::::|
     2 |       |:::::::|  |#|  |:::::::|       |:::::::|       |:::::::|
       |       |:::::::| /###\ |:::::::|       |:::::::|       |:::::::|
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |:::::::|       |:::::::|       |:::::::|  (V)  |:::::::|       |
     1 |:::::::|       |:::::::|       |:::::::|  )#(  |:::::::|       |
       |:::::::|       |:::::::|       |:::::::| /###\ |:::::::|       |
       +-------+-------+-------+-------+-------+-------+-------+-------+
           a       b       c       d       e       f       g       h

    [White "Genetic AI 1603"]
    [Black "Genetic AI 1573"]
    [Result "ERROR:"]
    [Termination "bad variation code"]

    1. f4 d5
    2. Nc3 Qd6
    3. Nxd5 Qxf4
    4. Nxc7+ Qxc7 { Qxc7 c4 }
    5. c4 Qxh2
    6. Qa4+ Nc6
    7. Qxc6+ bxc6
    8. d4 Qxh1
    9. Bg5 Qxg2
    10. O-O-O Qxe2
    11. Bxe2 e5
    12. dxe5 Bd6
    13. Rxd6 f6
    14. Bxf6 gxf6
    15. Bh5+ { Bh5+ Kf8 } Ke7
    16. Nf3 fxe5
    17. Rxc6 Bb7
    18. Rc8 Rxc8
    19. Bg4 Rxc4+ { Rxc4+ Kd2 }
    20. Kd1 Rxg4
    21. Nxe5 Rg2
    22. Nf7 Kxf7
    23. a4 Be4
    24. b3 Ke6
    25. a5 Ra2 { Ra2 Ke1 }
    26. a6 Bd3
    27. Kc1 Rc2+ { Rc2+ Kd1 }
    28. Kb1 Ke5 { Ke5 b4 }
    29. b4 { b4 h5 Ka1 } h5 { h5 Ka1 }
    30. Ka1 { Ka1 Rh2 b5 } Rd2 { Rd2 b5 }
    31. b5 Rh6 { Rh6 b6 axb6 a7 }
    32. b6 axb6 { axb6 a7 Rh7 }
    33. a7 Re2
    34. a8=R Be4
    35. Rd8 Kf6
    36. Rd2 Bd3
    37. Rxe2 { Rxe2 Bxe2 Kb2 } Bxe2 { Bxe2 Kb2 }
    38. Kb1 { Kb1 Ke5 Kc2 } Ke5 { Ke5 Kc2 }
    39. Kc2 { Kc2 Rc6+ Kd2 } Rc6+ { Rc6+ Kd2 }
    40. Kd2 { Kd2 Rc4 } Bf1 { Bf1 Ke3 }
    41. Ke3 { Ke3 h4 Kf3 Nh6 Kf2 } Rc2 { Rc2 Kf3 }
    42. Kf3 Nh6 { Nh6 Kg3 Nf5+ Kf3 }

    Current principal variation: Kf3 Nh6 Kf2
    Depth: 0
    Next move in variation: Kf2

The current principal variation comes from cutting off the first two
moves of the variation found by white in move 41. The first two moves
were cut off due to white's move 42 being forced. But, the second move
of the variation (h4) was not followed by black (Rc2), but this was not
realized since the moves were cut off before comparing it to the game
history. This resulted in the attempt to try the next move in the
variation (Kf2) even though it was now an illegal move.

Final actual board state upon Genetic_AI::choose_move() call

       +-------+-------+-------+-------+-------+-------+-------+-------+
       |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
     8 |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
       |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |:::::::|       |:::::::|       |:::::::|       |:::::::|       |
     7 |:::::::|       |:::::::|       |:::::::|       |:::::::|       |
       |:::::::|       |:::::::|       |:::::::|       |:::::::|       |
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |       |:  _  :|       |:::::::|       |:::::::|       |: /") :|
     6 |       |: (#) :|       |:::::::|       |:::::::|       |: 7#( :|
       |       |:/###\:|       |:::::::|       |:::::::|       |:/###\:|
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |:::::::|       |:::::::|       |: \+/ :|       |:::::::|   _   |
     5 |:::::::|       |:::::::|       |: |#| :|       |:::::::|  (#)  |
       |:::::::|       |:::::::|       |:/###\:|       |:::::::| /###\ |
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
     4 |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
       |       |:::::::|       |:::::::|       |:::::::|       |:::::::|
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |:::::::|       |:::::::|       |:::::::|  \+/  |:::::::|       |
     3 |:::::::|       |:::::::|       |:::::::|  | |  |:::::::|       |
       |:::::::|       |:::::::|       |:::::::| /___\ |:::::::|       |
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |       |:::::::|  |U|  |:::::::|       |:::::::|       |:::::::|
     2 |       |:::::::|  |#|  |:::::::|       |:::::::|       |:::::::|
       |       |:::::::| /###\ |:::::::|       |:::::::|       |:::::::|
       +-------+-------+-------+-------+-------+-------+-------+-------+
       |:::::::|       |:::::::|       |:::::::|  (V)  |:::::::|       |
     1 |:::::::|       |:::::::|       |:::::::|  )#(  |:::::::|       |
       |:::::::|       |:::::::|       |:::::::| /###\ |:::::::|       |
       +-------+-------+-------+-------+-------+-------+-------+-------+
           a       b       c       d       e       f       g       h

    ERROR: ERROR: bad variation code

    Process returned 1 (0x1)   execution time : 4048.598 s
    Press ENTER to continue.